### ISSUE TITLE
Javascript Full-stack Junior Developer 

### ISSUE THREAD

**Issue by filipenevola** [quavedev/join#2]
## About the company

Read [here](https://github.com/quavedev/join/blob/main/README.md) how Quave works and what is expected from you.

## Job Description

Develop features and fix bugs in our products and when prepared also in client's projects. 

You be mentored by senior developers closely, coding in pair and receiving feedback on Pull requests. 

## How to Apply

Solve our [code challenge](https://github.com/quavedev/code-challenge)

**Comment by Mateusnasciment** [comment]
Olá, meu nome é Mateus e estou em busca de uma oportunidade na área de programação. Tenho habilidades em diversas linguagens, incluindo Typescript, JavaScript, php, golang e Python, nas quais tenho experiência de 2 anos, respectivamente. Para mostrar um pouco das minhas habilidades, criei um portfólio que está disponível para avaliação. Estou animado para contribuir com meus conhecimentos e crescer profissionalmente na área de programação.

	 https://archlinux-drab.vercel.app

https://github.com/Mateusnasciment
https://www.linkedin.com/in/mateusnasciment/

**Comment by VINIA6** [comment]
Olá meu nome é Vinícius, sou apaixonado por resolver problemas complexos por meio de programação e gosto de me manter atualizado com as últimas tendências e tecnologias. Trabalhar em equipe sempre foi uma grande oportunidade de aprender e compartilhar conhecimento, exaltando assim o Team-Oriented. Estou disposto a combinar soft skills e experiência técnica para entregar resultados precisos. Segue abaixo meu GitHub e Linkedin:

https://www.linkedin.com/in/vinia6/
https://github.com/VINIA6

**Comment by filipenevola** [comment]
> Bom dia, tenho interesse

Resolva o [desafio](https://github.com/quavedev/code-challenge). Leia tudo antes de começar.

**Comment by filipenevola** [comment]
> Olá, meu nome é Mateus e estou em busca de uma oportunidade na área de programação. Tenho habilidades em diversas linguagens, incluindo Typescript, JavaScript, php, golang e Python, nas quais tenho experiência de 2 anos, respectivamente. Para mostrar um pouco das minhas habilidades, criei um portfólio que está disponível para avaliação. Estou animado para contribuir com meus conhecimentos e crescer profissionalmente na área de programação.
> 
> ```
>  https://archlinux-drab.vercel.app
> ```
> 
> https://github.com/Mateusnasciment https://www.linkedin.com/in/mateusnasciment/



Resolva o [desafio](https://github.com/quavedev/code-challenge). Leia tudo antes de começar.

**Comment by filipenevola** [comment]
> Olá meu nome é Vinícius, sou apaixonado por resolver problemas complexos por meio de programação e gosto de me manter atualizado com as últimas tendências e tecnologias. Trabalhar em equipe sempre foi uma grande oportunidade de aprender e compartilhar conhecimento, exaltando assim o Team-Oriented. Estou disposto a combinar soft skills e experiência técnica para entregar resultados precisos. Segue abaixo meu GitHub e Linkedin:
> 
> https://www.linkedin.com/in/vinia6/ https://github.com/VINIA6



Resolva o [desafio](https://github.com/quavedev/code-challenge). Leia tudo antes de começar.

**Comment by filipenevola** [comment]
Just position was fulfilled this Monday.
