### ISSUE TITLE
Javascript Full-stack Regular Developer

### ISSUE THREAD

**Issue by filipenevola** [quavedev/join#5]
## About the company

Read [here](https://github.com/quavedev/join/blob/main/README.md) how Quave works and what is expected from you.

## Job Description

Develop features and fix bugs in our client's projects. 

You will help Junior developers with their tasks.

You will be mentored by senior developers closely, coding in pairs and receiving feedback on Pull requests frequently. 

## Monthly Payment

$ 2,400 USD

> Don't apply for this position if you want to make more than that. This is the top limit for this position.

## How to Apply

Solve our [code challenge](https://github.com/quavedev/code-challenge)

**Comment by omarcusmoreira** [comment]
Hi FIlipe I'm having an issue with the coding challenge:
![image](https://github.com/quavedev/join/assets/33607358/758208ce-9ec0-4987-9a5f-63adea97f6c5)

**Comment by filipenevola** [comment]
> Hi FIlipe I'm having an issue with the coding challenge

I see others solving the challenge without any issues, and we try to help as little as possible to keep everybody on fair ground.

**Comment by matheusccastroo** [comment]
We hired someone for this position! 🎉
