### ISSUE TITLE
Javascript Full-stack Senior Developer 

### ISSUE THREAD

**Issue by filipenevola** [quavedev/join#6]
## About the company

Read [here](https://github.com/quavedev/join/blob/main/README.md) how Quave works and what is expected from you.

## Job Description

Develop features and fix bugs in our client's projects. 

You will help Junior and Regular developers with their tasks.

You will pair with other senior developers closely to improve your coding skills. 

## Monthly Payment

$ 3,800 USD

> Don't apply for this position if you want to make more than that. This is the top limit for this position.

## How to Apply

Solve our [code challenge](https://github.com/quavedev/code-challenge)

**Comment by matheusccastroo** [comment]
We hired someone for this position! 🎉
